### ISSUE TITLE
Pull in Preprints from Preprint Servers

### ISSUE THREAD

**Issue by lightninglu10** [ResearchHub/researchhub-backend#326]
- [x] arxiv.org , http://export.arxiv.org/api/ , http://arxiv-sanity.com/
- [x] biorxiv https://www.biorxiv.org/ , https://www.rxivist.org/docs , https://hub.docker.com/r/blekhmanlab/rxivist_data , https://github.com/blekhmanlab/rxivist , https://www.biorxiv.org/tdm
- [x] elife https://elifesciences.org/ , https://api.elifesciences.org/documentation/, https://prod--gateway.elifesciences.org/documentation/

Aggregators
- [ ] OSF open science framework https://developer.osf.io/# (socarxiv)
- [ ] OpenAPI https://docs.figshare.com/ (can be used the https://www.techrxiv.org/ and https://chemrxiv.org/f/faqs#faq-11 for example)

Worth looking into
- [ ] Zenodo https://zenodo.readthedocs.io/en/latest/usage.html , https://developers.zenodo.org/#oai-pmh (looks like metadata only)

List of 50 preprint servers

https://docs.google.com/spreadsheets/d/17RgfuQcGJHKSsSJwZZn0oiXAnimZu2sZsWp8Z6ZaYYo/edit#gid=0

COVID-19 Pre print server

We want to potentially pull in all PDF's across preprint servers on the web. First let's look into the API's and understand -- can this be done?
